import math
print(3+4)
print(3-4)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print(3//4)
print("William Stroud\n")
print("England\n")
print("I am enjoying 30 days of python")
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type("William Stroud"))
print(type("England"))
print(type("h"))
print("The Euclidean distance between (2,3) & (10,8) is: " + str(math.sqrt(((10-2)**2) + ((8-3)**2))))